site_name: Paisa
nav:
  - index.md
  - 'Getting Starteed':
    - getting-started/installation.md
    - getting-started/tutorial.md
  - 'Reference':
    - reference/accounts.md
    - reference/commodities.md
    - reference/allocation-targets.md
    - reference/budget.md
    - reference/bulk-edit.md
    - reference/import.md
    - reference/retirement.md
    - reference/recurring.md
    - reference/config.md
    - reference/ledger-cli.md
    - reference/analysis.md
    - 'Tax':
      - reference/tax/index.md
      - reference/tax/tax-harvesting.md
      - reference/tax/capital-gains.md
      - reference/tax/schedule-al.md
  - 'Demo': 'https://demo.paisa.fyi'

theme:
  name: material
  icon:
    logo: material/currency-rupee
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/extra.js

copyright: Copyright &copy; 2022 - 2023 Anantha Kumaran
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ananthakumaran/paisa
    - icon: simple/matrix
      link: https://matrix.to/#/#paisa:matrix.org
