name: Docs

on:
  - push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: publish
      run: make publish
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        BRANCH: gh-pages
        FOLDER: docs/book
