name: Release

on:
  push:
    tags:
      - '*'

jobs:
  linux-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix-shell --run 'npm install'
        nix-shell --run './node_modules/.bin/esbuild web/src/index.ts --bundle --outfile=web/static/dist.js'
        nix-shell --run 'go build'
        cp paisa paisa-linux-amd64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  mac-binary:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - run: |
        brew update
        brew install --force --overwrite go sqlite3
        npm install
        ./node_modules/.bin/esbuild web/src/index.ts --bundle --outfile=web/static/dist.js
        go build
        cp paisa paisa-darwin-amd64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
